# coding: utf-8

"""
    Open API Hub API

    API specification for Open API Hub project. This API is designed to manage users, projects, project members, API specifications, and project credentials.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from api_hub.apis.api_specs_api import router as APISpecsApiRouter
from api_hub.apis.project_credentials_api import router as ProjectCredentialsApiRouter
from api_hub.apis.project_members_api import router as ProjectMembersApiRouter
from api_hub.apis.projects_api import router as ProjectsApiRouter
from api_hub.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="Open API Hub API",
    description="API specification for Open API Hub project. This API is designed to manage users, projects, project members, API specifications, and project credentials.",
    version="1.0.0",
)

app.include_router(APISpecsApiRouter)
app.include_router(ProjectCredentialsApiRouter)
app.include_router(ProjectMembersApiRouter)
app.include_router(ProjectsApiRouter)
app.include_router(UsersApiRouter)
